# core/sector_mapping.py

SECTOR_MAP = {
    # NIFTY AUTO
    'ASHOKLEY': 'NIFTY AUTO', 'BAJAJ-AUTO': 'NIFTY AUTO', 'BHARATFORG': 'NIFTY AUTO', 'BOSCHLTD': 'NIFTY AUTO',
    'EICHERMOT': 'NIFTY AUTO', 'FORCEMOT': 'NIFTY AUTO', 'HEROMOTOCO': 'NIFTY AUTO', 'HYUNDAI': 'NIFTY AUTO',
    'M&M': 'NIFTY AUTO', 'MARUTI': 'NIFTY AUTO', 'MOTHERSON': 'NIFTY AUTO', 'SONACOMS': 'NIFTY AUTO',
    'TATAMOTORS': 'NIFTY AUTO', 'TIINDIA': 'NIFTY AUTO', 'TMPV': 'NIFTY AUTO', 'TVSMOTOR': 'NIFTY AUTO',
    'UNOMINDA': 'NIFTY AUTO',

    # NIFTY BANK / PSU BANK
    'AUBANK': 'NIFTY BANK', 'AXISBANK': 'NIFTY BANK', 'BANDHANBNK': 'NIFTY BANK', 'BANKBARODA': 'NIFTY PSU BANK',
    'BANKINDIA': 'NIFTY PSU BANK', 'CANBK': 'NIFTY PSU BANK', 'FEDERALBNK': 'NIFTY BANK', 'HDFCBANK': 'NIFTY BANK',
    'ICICIBANK': 'NIFTY BANK', 'IDFCFIRSTB': 'NIFTY BANK', 'INDIANB': 'NIFTY PSU BANK', 'INDUSINDBK': 'NIFTY BANK',
    'KOTAKBANK': 'NIFTY BANK', 'PNB': 'NIFTY PSU BANK', 'RBLBANK': 'NIFTY BANK', 'SBIN': 'NIFTY PSU BANK',
    'UNIONBANK': 'NIFTY PSU BANK', 'YESBANK': 'NIFTY BANK',

    # NIFTY FIN SERVICE
    '360ONE': 'NIFTY FIN SERVICE', 'ABCAPITAL': 'NIFTY FIN SERVICE', 'ANGELONE': 'NIFTY FIN SERVICE',
    'BAJFINANCE': 'NIFTY FIN SERVICE', 'BAJAJFINSV': 'NIFTY FIN SERVICE', 'BAJAJHLDNG': 'NIFTY FIN SERVICE',
    'BSE': 'NIFTY FIN SERVICE', 'CAMS': 'NIFTY FIN SERVICE', 'CDSL': 'NIFTY FIN SERVICE', 'CHOLAFIN': 'NIFTY FIN SERVICE',
    'HDFCAMC': 'NIFTY FIN SERVICE', 'HDFCLIFE': 'NIFTY FIN SERVICE', 'ICICIGI': 'NIFTY FIN SERVICE',
    'ICICIPRULI': 'NIFTY FIN SERVICE', 'IEX': 'NIFTY FIN SERVICE', 'IREDA': 'NIFTY FIN SERVICE',
    'IRFC': 'NIFTY FIN SERVICE', 'JIOFIN': 'NIFTY FIN SERVICE', 'KFINTECH': 'NIFTY FIN SERVICE',
    'LICHSGFIN': 'NIFTY FIN SERVICE', 'LICI': 'NIFTY FIN SERVICE', 'LTF': 'NIFTY FIN SERVICE',
    'MANAPPURAM': 'NIFTY FIN SERVICE', 'MCX': 'NIFTY FIN SERVICE', 'MFSL': 'NIFTY FIN SERVICE',
    'MOTILALOFS': 'NIFTY FIN SERVICE', 'MUTHOOTFIN': 'NIFTY FIN SERVICE', 'NAM-INDIA': 'NIFTY FIN SERVICE',
    'PAYTM': 'NIFTY FIN SERVICE', 'PFC': 'NIFTY FIN SERVICE', 'PNBHOUSING': 'NIFTY FIN SERVICE',
    'POLICYBZR': 'NIFTY FIN SERVICE', 'RECLTD': 'NIFTY FIN SERVICE', 'SBICARD': 'NIFTY FIN SERVICE',
    'SBILIFE': 'NIFTY FIN SERVICE', 'SHRIRAMFIN': 'NIFTY FIN SERVICE',

    # NIFTY IT
    'COFORGE': 'NIFTY IT', 'HCLTECH': 'NIFTY IT', 'INFY': 'NIFTY IT', 'KPITTECH': 'NIFTY IT',
    'LTM': 'NIFTY IT', 'MPHASIS': 'NIFTY IT', 'NAUKRI': 'NIFTY IT', 'OFSS': 'NIFTY IT',
    'PERSISTENT': 'NIFTY IT', 'TATAELXSI': 'NIFTY IT', 'TCS': 'NIFTY IT', 'TECHM': 'NIFTY IT',
    'WIPRO': 'NIFTY IT',

    # NIFTY PHARMA & HEALTHCARE
    'ALKEM': 'NIFTY PHARMA', 'APOLLOHOSP': 'NIFTY PHARMA', 'AUROPHARMA': 'NIFTY PHARMA', 'BIOCON': 'NIFTY PHARMA',
    'CIPLA': 'NIFTY PHARMA', 'DIVISLAB': 'NIFTY PHARMA', 'DRREDDY': 'NIFTY PHARMA', 'FORTIS': 'NIFTY PHARMA',
    'GLENMARK': 'NIFTY PHARMA', 'LAURUSLABS': 'NIFTY PHARMA', 'LUPIN': 'NIFTY PHARMA', 'MANKIND': 'NIFTY PHARMA',
    'MAXHEALTH': 'NIFTY PHARMA', 'SUNPHARMA': 'NIFTY PHARMA', 'TORNTPHARM': 'NIFTY PHARMA', 'ZYDUSLIFE': 'NIFTY PHARMA',

    # NIFTY REALTY
    'DLF': 'NIFTY REALTY', 'GODREJPROP': 'NIFTY REALTY', 'LODHA': 'NIFTY REALTY', 'OBEROIRLTY': 'NIFTY REALTY',
    'PHOENIXLTD': 'NIFTY REALTY', 'PRESTIGE': 'NIFTY REALTY', 'NBCC': 'NIFTY REALTY',

    # NIFTY METAL
    'APLAPOLLO': 'NIFTY METAL', 'HINDALCO': 'NIFTY METAL', 'HINDZINC': 'NIFTY METAL', 'JINDALSTEL': 'NIFTY METAL',
    'JSWSTEEL': 'NIFTY METAL', 'NATIONALUM': 'NIFTY METAL', 'NMDC': 'NIFTY METAL', 'SAIL': 'NIFTY METAL',
    'TATASTEEL': 'NIFTY METAL', 'VEDL': 'NIFTY METAL',

    # NIFTY FMCG & CONSUMPTION
    'BRITANNIA': 'NIFTY FMCG', 'COLPAL': 'NIFTY FMCG', 'DABUR': 'NIFTY FMCG', 'GODFRYPHLP': 'NIFTY FMCG',
    'GODREJCP': 'NIFTY FMCG', 'HINDUNILVR': 'NIFTY FMCG', 'ITC': 'NIFTY FMCG', 'MARICO': 'NIFTY FMCG',
    'NESTLEIND': 'NIFTY FMCG', 'PATANJALI': 'NIFTY FMCG', 'RADICO': 'NIFTY FMCG', 'TATACONSUM': 'NIFTY FMCG',
    'UNITDSPR': 'NIFTY FMCG', 'VBL': 'NIFTY FMCG', 'ASIANPAINT': 'NIFTY CONSUMPTION', 'DMART': 'NIFTY CONSUMPTION',
    'INDHOTEL': 'NIFTY CONSUMPTION', 'JUBLFOOD': 'NIFTY CONSUMPTION', 'KALYANKJIL': 'NIFTY CONSUMPTION',
    'PAGEIND': 'NIFTY CONSUMPTION', 'TITAN': 'NIFTY CONSUMPTION', 'TRENT': 'NIFTY CONSUMPTION',
    'NYKAA': 'NIFTY CONSUMPTION', 'SWIGGY': 'NIFTY CONSUMPTION', 'ETERNAL': 'NIFTY CONSUMPTION',
    'VMM': 'NIFTY CONSUMPTION',

    # NIFTY ENERGY / OIL & GAS / POWER / PSE
    'ADANIENSOL': 'NIFTY ENERGY', 'ADANIGREEN': 'NIFTY ENERGY', 'ADANIPOWER': 'NIFTY ENERGY',
    'BPCL': 'NIFTY ENERGY', 'COALINDIA': 'NIFTY ENERGY', 'GAIL': 'NIFTY ENERGY', 'HINDPETRO': 'NIFTY ENERGY',
    'IOC': 'NIFTY ENERGY', 'INOXWIND': 'NIFTY ENERGY', 'JSWENERGY': 'NIFTY ENERGY', 'NHPC': 'NIFTY ENERGY',
    'NTPC': 'NIFTY ENERGY', 'OIL': 'NIFTY ENERGY', 'ONGC': 'NIFTY ENERGY', 'PETRONET': 'NIFTY ENERGY',
    'POWERGRID': 'NIFTY ENERGY', 'PREMIERENE': 'NIFTY ENERGY', 'RELIANCE': 'NIFTY ENERGY',
    'SUZLON': 'NIFTY ENERGY', 'TATAPOWER': 'NIFTY ENERGY', 'WAAREEENER': 'NIFTY ENERGY',

    # NIFTY INFRA & CAPITAL GOODS & DEFENSE
    'ABB': 'NIFTY INFRA', 'ADANIENT': 'NIFTY INFRA', 'ADANIPORTS': 'NIFTY INFRA', 'AMBER': 'NIFTY INFRA',
    'AMBUJACEM': 'NIFTY INFRA', 'ASTRAL': 'NIFTY INFRA', 'BDL': 'NIFTY INFRA', 'BEL': 'NIFTY INFRA',
    'BHEL': 'NIFTY INFRA', 'BHARTIARTL': 'NIFTY INFRA', 'BLUESTARCO': 'NIFTY INFRA', 'CGPOWER': 'NIFTY INFRA',
    'COCHINSHIP': 'NIFTY INFRA', 'CONCOR': 'NIFTY INFRA', 'CROMPTON': 'NIFTY INFRA', 'CUMMINSIND': 'NIFTY INFRA',
    'DALBHARAT': 'NIFTY INFRA', 'DELHIVERY': 'NIFTY INFRA', 'DIXON': 'NIFTY INFRA', 'GMRAIRPORT': 'NIFTY INFRA',
    'GRASIM': 'NIFTY INFRA', 'GVT&D': 'NIFTY INFRA', 'HAL': 'NIFTY INFRA', 'HAVELLS': 'NIFTY INFRA',
    'INDIGO': 'NIFTY INFRA', 'INDUSTOWER': 'NIFTY INFRA', 'KAYNES': 'NIFTY INFRA', 'KEI': 'NIFTY INFRA',
    'LT': 'NIFTY INFRA', 'MAZDOCK': 'NIFTY INFRA', 'PGEL': 'NIFTY INFRA', 'PIDILITIND': 'NIFTY INFRA',
    'PIIND': 'NIFTY INFRA', 'POLYCAB': 'NIFTY INFRA', 'POWERINDIA': 'NIFTY INFRA', 'RVNL': 'NIFTY INFRA',
    'SHREECEM': 'NIFTY INFRA', 'SIEMENS': 'NIFTY INFRA', 'SOLARINDS': 'NIFTY INFRA', 'SRF': 'NIFTY INFRA',
    'SUPREMEIND': 'NIFTY INFRA', 'ULTRACEMCO': 'NIFTY INFRA', 'UPL': 'NIFTY INFRA', 'VOLTAS': 'NIFTY INFRA',
    'IDEA': 'NIFTY INFRA',
}

def get_sector_for_symbol(symbol: str) -> str:
    """Returns the NSE Sector Index name for a given FNO symbol. Defaults to NIFTY 50."""
    return SECTOR_MAP.get(symbol, "NIFTY 50")
